services:
  php-8.3:
    image: php:8.3-apache
    container_name: php-8.3
    ports:
      - "81:80"
      - "8000:8000"
    command: >
      sh -c "
        apt-get update
        apt-get install -y libcurl4-openssl-dev
        a2enmod headers
        a2enmod rewrite
        docker-php-ext-install curl mysqli pdo pdo_mysql
        docker-php-ext-enable pdo_mysql
        cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
        sed -i 's/memory_limit = .*/memory_limit = -1/' /usr/local/etc/php/php.ini
        sed -i '1i\ServerName localhost:81' /etc/apache2/apache2.conf
        chown -R www-data:www-data /var/www
        apache2-foreground
      "
    volumes:
      - ../src:/var/www/html
  composer-2.8.2:
    image: composer:2.8.2
    container_name: composer-2.8.2
    volumes:
      - ../:/app
      - ../.composer:/root/.composer
    command: >
      sh -c "
        tail -f /dev/null
      "
  mysql-9:
    image: mysql:9
    container_name: mysql-9
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - ./data/mysql:/var/lib/mysql


