services:
  php-8.3:
    image: php:8.3-apache
    container_name: php-8.3
    ports:
      - "8001:80"
      - "8000:8000"
    command: >
      sh -c "
        apt-get update
        apt-get install -y libcurl4-openssl-dev libzip-dev unzip
        
        a2enmod headers
        a2enmod rewrite
        
        docker-php-ext-install zip curl mysqli pdo pdo_mysql
        docker-php-ext-enable pdo_mysql
        
        cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
        sed -i 's/memory_limit = .*/memory_limit = -1/' /usr/local/etc/php/php.ini
        sed -i '1i\ServerName localhost:8001' /etc/apache2/apache2.conf
        
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        composer install
      
        curl -fsSL https://deb.nodesource.com/setup_23.x -o nodesource_setup.sh 
        -E bash nodesource_setup.sh 
        apt-get install -y nodejs
        
        curl -O https://www.npmjs.com/install.sh 
        sh install.sh
      
        npm install
        npm run build 
        
        php artisan migrate
        chown -R www-data:www-data /var/www
        apache2-foreground
      "
    volumes:
      - ../src:/var/www/html
    depends_on:
      - mysql-9
  mysql-9:
    image: mysql:9
    container_name: mysql-9
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - ./data/mysql:/var/lib/mysql


